import '@/tokens/index.scss';
import '@/styles/index.scss';

import type { Metadata } from 'next';

import cn from 'classnames';

import { font } from '@/resources';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        data-neutral="gray"
        data-brand="indigo"
        className={cn(font.primary.variable)}
      >
        {children}
      </body>
    </html>
  );
}
